// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Pklerik/alice-skill/internal/store (interfaces: MessageStore)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	store "github.com/Pklerik/alice-skill/internal/store"
	gomock "github.com/golang/mock/gomock"
)

// MockMessageStore is a mock of MessageStore interface.
type MockMessageStore struct {
	ctrl     *gomock.Controller
	recorder *MockMessageStoreMockRecorder
}

// MockMessageStoreMockRecorder is the mock recorder for MockMessageStore.
type MockMessageStoreMockRecorder struct {
	mock *MockMessageStore
}

// NewMockMessageStore creates a new mock instance.
func NewMockMessageStore(ctrl *gomock.Controller) *MockMessageStore {
	mock := &MockMessageStore{ctrl: ctrl}
	mock.recorder = &MockMessageStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageStore) EXPECT() *MockMessageStoreMockRecorder {
	return m.recorder
}

// FindRecipient mocks base method.
func (m *MockMessageStore) FindRecipient(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRecipient", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRecipient indicates an expected call of FindRecipient.
func (mr *MockMessageStoreMockRecorder) FindRecipient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRecipient", reflect.TypeOf((*MockMessageStore)(nil).FindRecipient), arg0, arg1)
}

// GetMessage mocks base method.
func (m *MockMessageStore) GetMessage(arg0 context.Context, arg1 int64) (*store.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", arg0, arg1)
	ret0, _ := ret[0].(*store.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMessageStoreMockRecorder) GetMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMessageStore)(nil).GetMessage), arg0, arg1)
}

// ListMessages mocks base method.
func (m *MockMessageStore) ListMessages(arg0 context.Context, arg1 string) ([]store.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", arg0, arg1)
	ret0, _ := ret[0].([]store.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockMessageStoreMockRecorder) ListMessages(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockMessageStore)(nil).ListMessages), arg0, arg1)
}

// SaveMessage mocks base method.
func (m *MockMessageStore) SaveMessage(arg0 context.Context, arg1 string, arg2 store.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageStoreMockRecorder) SaveMessage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageStore)(nil).SaveMessage), arg0, arg1, arg2)
}
